import i18n from 'i18next';
import { initReactI18next } from 'react-i18next';
import LanguageDetector from 'i18next-browser-languagedetector';

i18n
    .use(LanguageDetector)
    .use(initReactI18next)
    .init({
        resources: {
            en: {
                translation: {
                    "Sales": "Sales",
                    "Species": "Species",
                    "Suppliers": "Suppliers",
                    "Inventory": "Inventory",
                    "Catalog": "Catalog",
                    "Reports": "Reports",
                    "Dashboard": "Dashboard",
                    "Stock": "Stock",
                    "Mortality": "Mortality",
                    "Valuation": "Valuation",

                    "Load Stock Report": "Load Stock Report",

                    // Reports
                    "Export CSV": "Export CSV",
                    "Export PDF": "Export PDF",
                    "Export Report": "Export Report",

                    "Stock Report": "Stock Report",
                    "Mortality Report": "Mortality Report",
                    "Sales Report": "Sales Report",
                    "Valuation Report": "Valuation Report",

                    "Summary": "Summary",
                    "Date": "Date",
                    "Page": "Page",
                    "of": "of",
                    "No data available": "No data available",
                    "Generated by Aquarium Manager": "Generated by Aquarium Manager",

                    "Select date range": "Select date range",
                    "Failed to load stock report": "Failed to load stock report",
                    "Failed to load mortality report": "Failed to load mortality report",
                    "Failed to load sales report": "Failed to load sales report",
                    "Failed to load valuation report": "Failed to load valuation report",

                    // Catalog, species and inventory fields
                    "Category": "Category",
                    "Current Stock": "Current Stock",
                    "Cost Value": "Cost Value",
                    "Available": "Available",
                    "ScientificName": "Scientific Name",
                    "CommonName": "Common Name",
                    "Variety": "Variety",
                    "Units Available": "Units Available",
                    "Oldest Lot": "Oldest Lot",
                    "Search by name, scientific name or category...": "Search by name, scientific name or category...",
                    "Search lots...": "Search lots...",
                    "Create Lot": "Create Lot",
                    "Inventory Lots": "Inventory Lots",
                    "Arrival Date": "Arrival Date",
                    "Initial Qty": "Initial Qty",
                    "Status": "Status",
                    "Actions": "Actions",
                    "Empty": "Empty",
                    "Low": "Low",
                    "lots tracked": "lots tracked",

                    // Dashboard
                    "Total Species": "Total Species",
                    "Total Stock": "Total Stock",
                    "Total Sales": "Total Sales",
                    "Revenue": "Revenue",
                    "Active species in catalog": "Active species in catalog",
                    "Units across all inventory": "Units across all inventory",
                    "Transactions recorded": "Transactions recorded",
                    "Total sales revenue": "Total sales revenue",
                    "Error loading dashboard": "Error loading dashboard",
                    "Quick Actions": "Quick Actions",
                    "Add Species": "Add Species",
                    "New Inventory": "New Inventory",
                    "Record Sale": "Record Sale",
                    "View Reports": "View Reports",
                    "Recent Sales": "Recent Sales",
                    "View All": "View All",
                    "Low Stock Alert": "Low Stock Alert",
                    "{count} species with low stock levels": "{count} species with low stock levels",
                    "Welcome to your Aquarium Manager": "Welcome to your Aquarium Manager",
                }
            },
            es: {
                translation: {
                    "Aquarium Manager": "Administrador de Acuario",
                    "Sales": "Ventas",
                    "Species": "Especies",
                    "Suppliers": "Proveedores",
                    "Supplier": "Proveedor",
                    "Inventory": "Inventario",
                    "Catalog": "Catálogo",
                    "Reports": "Reportes",
                    "Dashboard": "Tablero",
                    "Stock": "Stock",
                    "Mortality": "Mortalidad",
                    "Valuation": "Valoración",

                    "Load Stock Report": "Cargar Reporte de Stock",

                    // Reports
                    "Export CSV": "Exportar CSV",
                    "Export PDF": "Exportar PDF",
                    "Export Report": "Exportar Reporte",

                    "Stock Report": "Reporte de Stock",
                    "Mortality Report": "Reporte de Mortalidad",
                    "Sales Report": "Reporte de Ventas",
                    "Valuation Report": "Reporte de Valoración",

                    "Summary": "Resumen",
                    "Date": "Fecha",
                    "Page": "Página",
                    "of": "de",
                    "No data available": "Sin datos disponibles",
                    "Generated by Aquarium Manager": "Generado por Administrador de Acuario",

                    "Select date range": "Seleccionar rango de fechas",
                    "Failed to load stock report": "Error al cargar el reporte de stock",
                    "Failed to load mortality report": "Error al cargar el reporte de mortalidad",
                    "Failed to load sales report": "Error al cargar el reporte de ventas",
                    "Failed to load valuation report": "Error al cargar el reporte de valoración",

                    // Catalog, species and inventory fields
                    // Reports
                    "Category": "Categoría",
                    "Current Stock": "Stock Actual",
                    "Cost Value": "Valor de Costo",

                    "Available": "Disponible",
                    "ScientificName": "Nombre Científico",
                    "CommonName": "Nombre Común",
                    "Variety": "Variedad",
                    "Units Available": "Unidades Disponibles",
                    "Oldest Lot": "Lote Más Antiguo",
                    "Search by name, scientific name or category...": "Buscar por nombre, nombre científico o categoría...",
                    "Search lots...": "Buscar lotes...",
                    "Create Lot": "Crear Lote",
                    "Inventory Lots": "Lotes de Inventario",
                    "Arrival Date": "Fecha de Llegada",
                    "Initial Qty": "Cantidad Inicial",
                    "Status": "Estado",
                    "Actions": "Acciones",
                    "Empty": "Vacío",
                    "Low": "Bajo",
                    "lots tracked": "lotes registrados",

                    // Dashboard
                    "Total Species": "Total de Especies",
                    "Total Stock": "Stock Total",
                    "Total Sales": "Ventas Totales",
                    "Revenue": "Ingresos",
                    "Active species in catalog": "Especies activas en el catálogo",
                    "Units across all inventory": "Unidades en todo el inventario",
                    "Transactions recorded": "Transacciones registradas",
                    "Total sales revenue": "Ingresos totales por ventas",
                    "Error loading dashboard": "Error al cargar el tablero",
                    "Quick Actions": "Acciones Rápidas",
                    "Add Species": "Agregar Especie",
                    "New Inventory": "Nuevo Inventario",
                    "Record Sale": "Registrar Venta",
                    "View Reports": "Ver Reportes",
                    "Recent Sales": "Ventas Recientes",
                    "View All": "Ver Todo",
                    "Low Stock Alert": "Alerta de Bajo Stock",
                    "{count} species with low stock levels": "{count} especies con niveles de stock bajos",
                    "Welcome to your Aquarium Manager": "Bienvenido a tu Administrador de Acuario"
                }
            }
        },

        lng: 'es',
        fallbackLng: 'en',
        interpolation: {
            escapeValue: false
        }
    });

    export default i18n;
